web:
        build: web
        restart: always
        container_name: civi_web
        environment:
                WEB_ROOT: /buildkit/build/CiviCRM
                VIRTUAL_HOST: civi.common.scot
        volumes_from:
                - app
        expose:
                - "80"
        links:
                - db
app:
        build: build
        environment:
                WEBROOT: /buildkit/build/CiviCRM
                CIVIVER: master
                SITE_TYPE: drupal-clean
                SITE_NAME: CommonSpace
                CMS_URL: civi.common.scot
                ADMIN_EMAIL: admin@common.scot
                ADMIN_PASS: C0mm0nW3Al
        volumes:
                - /buildkit/build/CiviCRM
                - /etc/ssmtp
        volumes_from:
                - db
        links:
                - db
        container_name: civi_build
db:
        image: mysql:5.5
        expose:
               - "3306"
        restart: always
        environment:
                MYSQL_ROOT_PASSWORD: 32720283b5fb32
                MYSQL_DATABASE: civi
                MYSQL_USER: civi
                MYSQL_PASSWORD: f90bff2494d
        container_name: civi_db
        volumes:
                - /var/lib/mysql

